### ISSUE TITLE
Add --update and --watch

### ISSUE THREAD

**Issue by ai** [ai/print-snapshots#1]
`--update` should call `jest [TESTS WITH SNAPSHOTS] -u` and print snapshots.

`--watch` should call `--update` on any `.js` file changes in the current project.

**Comment by ai** [comment]
@LordotU oh, I forgot to check an important part of this issue, which was mentioned at Cult of Martians.

In `--update` we need to call only tests with snapshots. We do not need to call all tests since it could be 10x slower.

So before calling `jest -u` we need to:
1. Collect `*.snap` files
2. Convert files content to test files names (like `index.test.js`) and test names (like `prints error message`)
3. We need to send to `jest` CLI only specific test files and specific tests (if it is possible to specify test by names).

**Comment by LordotU** [comment]
@ai Oh, I've found that issue just here and missed at the Cult site. Okay, will fix that.
